# Local Dev docker-compose
version: '2.2'
networks:
  default:
    name: website-development
services:
  nginx-dev:
    container_name: website-proxy-dev
    hostname: website-proxy-dev
    image: reverseproxy:latest
    build:
      dockerfile: ./development/Dockerfile-dev
      context: ..
    #environment:
    #  - AWS_ACCESS_KEY_ID
    #  - AWS_SECRET_ACCESS_KEY
    #  - REGION
    #  - CERT_NAME
    #  - DISTR_NAME
    #  - DOMAINS
    env_file: ../.env
    #working_dir:
    ports:
      - '8080:80'