version: '2.2'
networks:
  website:
    driver: bridge
volumes:
  static_volume:

services:
  nginx-dev:
    container_name: website-proxy-dev
    hostname: website-proxy-dev
    image: reverseproxy:latest
    build:
      dockerfile: ./development/Dockerfile-dev
      context: ..
    env_file: ../.env
    ports:
      - '8080:80'
    volumes:
    - static_volume:/app/staticfiles
    networks:
    - website

  
  django:
    container_name: land-collection
    image: landcollection:latest
    env_file: ../.env
    ports: 
      - '8000:8000'
    networks:
    - website
    volumes:
    - static_volume:/app/staticfiles
    depends_on:
      - nginx-dev






