# Local Dev docker-compose
version: '2.2'
networks:
  default:
    name: website-development
services:
  nginx-dev:
    container_name: wbesite-proxy-dev
    hostname: website-proxy-dev
    image: reverseproxy:latest
    build:
      dockerfile: ./development/Dockerfile-dev
      context: ..
    environment:
        - ENVIROMENT=dev
    #env_file: .env
    #working_dir:
    ports:
      - '8080:80'
      - '4433:443'