# prod docker-compose
version: '2.2'
networks:
  website:
    driver: bridge
volumes:
  static_volume:

services:
  nginx:
    container_name: website-proxy
    hostname: website-proxy
    image: reverseproxy:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - static_volume:/app/staticfiles
    networks:
    - website

  
  django:
    container_name: land-collection
    image: landcollection:latest
    env_file: .env
    ports: 
      - '8000:8000'
    networks:
    - website
    volumes:
    - static_volume:/app/staticfiles
    depends_on:
      - nginx



