# prod docker-compose
version: '2.2'
networks:
  default:
    name: website
services:
  nginx:
    container_name: website-proxy
    hostname: website-proxy
    image: reverseproxy:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    #environment:
    #  - AWS_ACCESS_KEY_ID
    #  - AWS_SECRET_ACCESS_KEY
    #  - REGION
    #  - CERT_NAME
    #  - DIST_NAME
    #  - DOMAINS
    env_file: .env
    #working_dir:
    ports:
      - '80:80'
      - '443:443'