# prod docker-compose
networks:
  website:
    driver: bridge
volumes:
  static_volume:

services:
  nginx:
    container_name: website-proxy
    hostname: website-proxy
    image: reverseproxy:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - static_volume:/app/staticfiles
    networks:
    - website



